### ISSUE TITLE
new wiki site

### ISSUE THREAD

**Issue by mck-sbs** [mck-sbs/PyConSys#3]
create  a wiki page with an explanation of evolutional algorithms

**Comment by ramvikrams** [comment]
Sir i can do it can you please explain what i have to do

**Comment by mck-sbs** [comment]
Hi,
can you explain the algorithm with graphics in English? Have a look at the source code or the graphic with explanation in German.

**Comment by ramvikrams** [comment]
Yes sir I read the code and explanation I can do it and as for the wiki page I have to do the explanation with graphics or I have to explain the code as well

**Comment by mck-sbs** [comment]
👍


Mit freundlichen Grüßen
 
Metin Karatas
__________________________
 
SBS Herzogenaurach-Höchstadt
Friedrich-Weiler-Platz 2
91074 Herzogenaurach
Tel. 09132/8023
Fax 09132/8024
www.sbs-herzogenaurach.de


Am 05.10.2022 um 17:52 schrieb ram vikram singh ***@***.***>:




﻿

Yes sir I read the code and explanation I can do it and as for the wiki page I have to do the explanation with graphics or I have to explain the code as well
—
Reply to this email directly, 
view it on GitHub, or 
unsubscribe.
You are receiving this because you authored the thread.Message
 ID: ***@***.***>

**Comment by ramvikrams** [comment]
Sir you want a Wikipedia page or a GitHub wiki page and one thing which I want to ask is the wiki page should include the the code explanation or the graphical explanation on the readme.md file or you want both.

**Comment by mck-sbs** [comment]
Github wiki page. Graphical explanation is ok. Next step could be the code explanation for a testbench file.


Mit freundlichen Grüßen
 
Metin Karatas
__________________________
 
SBS Herzogenaurach-Höchstadt
Friedrich-Weiler-Platz 2
91074 Herzogenaurach
Tel. 09132/8023
Fax 09132/8024
www.sbs-herzogenaurach.de


Am 05.10.2022 um 19:51 schrieb ram vikram singh ***@***.***>:




﻿

Sir you want a Wikipedia page or a GitHub wiki page and one thing which I want to ask is the wiki page should include the the code explanation or the graphical explanation on the readme.md file or you want both.
—
Reply to this email directly, 
view it on GitHub, or 
unsubscribe.
You are receiving this because you authored the thread.Message
 ID: ***@***.***>

**Comment by ramvikrams** [comment]
I understand it now sir I will start working on it but after 5 days my college exams will start so after 20th October I will start the main work. Will that be okay sir.


Mit freundlichen Grüßen

**Comment by mck-sbs** [comment]
That’s ok. Thank you for your help.


Mit freundlichen Grüßen
 
Metin Karatas
__________________________
 
SBS Herzogenaurach-Höchstadt
Friedrich-Weiler-Platz 2
91074 Herzogenaurach
Tel. 09132/8023
Fax 09132/8024
www.sbs-herzogenaurach.de


Am 05.10.2022 um 20:24 schrieb ram vikram singh ***@***.***>:




﻿

I understand it now sir I will start working on it but after 5 days my college exams will start so after 20th October I will start the main work. Will that be okay sir.
Mit freundlichen Grüßen
—
Reply to this email directly, 
view it on GitHub, or 
unsubscribe.
You are receiving this because you authored the thread.Message
 ID: ***@***.***>

**Comment by ramvikrams** [comment]
thank you sir for your your kind consideration

**Comment by ramvikrams** [comment]
Sir you are having a wiki page so what do I have to add
