### ISSUE TITLE
complex control loops

### ISSUE THREAD

**Issue by mck-sbs** [mck-sbs/PyConSys#4]
create a more complex example loop with pid, delay and two pt1 units

**Comment by virajone** [comment]
Hey, I wish to contribute. As I am new to the project and this seems like a good first issue, can you provide the scope for this issue with more details  ?

**Comment by mck-sbs** [comment]
Hi,
thank you for your interest. Have a look at the example "testbench_pid_pt2_evolution.py". You can modify it with two pt1 and one delay. Make a sketch of the control loop before coding it.

**Comment by himavamsianumula** [comment]
Hi, I would like to contribute. Can you guide me regarding what should I work on?

**Comment by mck-sbs** [comment]
Hi,
thank you for your interest. Have a look at the example "testbench_pid_pt2_evolution.py". You can modify it with two pt1 and one delay. Make a sketch of the control loop before coding it.

**Comment by loki4514** [comment]
Hi, 
I am new to open source contribution, can you suggest me what should i work on?

**Comment by mck-sbs** [comment]
Implented

**Comment by mck-sbs** [comment]
implemented
